### ISSUE TITLE
TypeError on execute()

### ISSUE THREAD

**Issue by asadowski10** [BeAPI/composer-scaffold-theme#11]
#### Version information

* Plugin version : 
* PHP : 8.0
* WordPress : 6.0

#### Error 

In Command.php line 301:
                                                                                                                                  
  [TypeError]                                                                                                                     
  Return value of "BEA\Composer\ScaffoldTheme\Command\ScaffoldThemeCommand::execute()" must be of the type int, "null" returned.  
                                                                                                                                  

Exception trace:
  at phar:///usr/local/Cellar/composer/2.3.7/bin/composer/vendor/symfony/console/Command/Command.php:301
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/Cellar/composer/2.3.7/bin/composer/vendor/symfony/console/Application.php:1024
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/Cellar/composer/2.3.7/bin/composer/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/Cellar/composer/2.3.7/bin/composer/src/Composer/Console/Application.php:335
 Composer\Console\Application->doRun() at phar:///usr/local/Cellar/composer/2.3.7/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/Cellar/composer/2.3.7/bin/composer/src/Composer/Console/Application.php:130
 Composer\Console\Application->run() at phar:///usr/local/Cellar/composer/2.3.7/bin/composer/bin/composer:88
 require() at /usr/local/Cellar/composer/2.3.7/bin/composer:29

scaffold-theme [--boilerplate-version [BOILERPLATE-VERSION]] [--no-autoload] [--] <folder>

**Comment by Rahe** [comment]
Fix : https://github.com/BeAPI/composer-scaffold-theme/pull/12

**Comment by Rahe** [comment]
Fixed in 1.3.3
